# This is controller file you can expect behvaiour change in processing code
# if any entry went wrong here
# All the things in the section will get converted to a df eventually
# If any section is there in json and variables are not getting formed please check json entry
# Also that df will also get renamed 

nested_delimiter: "-"

# This column must be there to map every data point to its id please provide exact path in json 
# You can add as many ids here this will then become part of your sections

mandatoryInformations:
  "App_id": "APP_ID"
  'created_date': 'created_date'

sections:
  transactions : 
      path: ['PIR:Data-Account']
      subsection_in_list_1: ['Xns-Xn']
      
transactions : 
    'App_id': 'App_id'
    'created_date': 'created_date'
    'date': '@date'
    'type': 'type'
    'description': '@narration'
    'amount': '@amount'
    'balance': '@balance'

#   transactions_2 : 
#       path: ['PIR:Data-Account-Xns-Xn']
#       txn_column_name:
#           'App_id': 'App_id'
#           'created_date': 'created_date'
#           'date': '@date'
#           'type': 'type'
#           'description': '@narration'
#           'amount': '@amount'
#           'balance': '@balance'
    
advancedConfigs:
    json_type: "dict"
    
    

# If any section is missing please put "null"