# Generated by Django 2.2.3 on 2020-02-20 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import live_scorecards.models
import picklefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Encoder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encoder_name', models.CharField(max_length=255)),
                ('encoder_pickle', picklefield.fields.PickledObjectField(editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LiveDataTransformer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('binary_transformer', models.BinaryField()),
                ('transformer_name', models.CharField(max_length=255)),
                ('folder_uuid', models.CharField(default=live_scorecards.models._get_uuid, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'folder_uuid')},
            },
        ),
        migrations.CreateModel(
            name='LiveDeploymentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ml_model_name', models.CharField(max_length=255)),
                ('trained_model_file', models.BinaryField()),
                ('isotonic_model', models.BinaryField(null=True)),
                ('oot_preds', picklefield.fields.PickledObjectField(editable=False, null=True)),
                ('probability_threshold', models.DecimalField(decimal_places=10, max_digits=12)),
                ('hard_class_prob_greater', models.BooleanField(null=True)),
                ('hard_class_prob_lower', models.BooleanField(null=True)),
                ('columns', picklefield.fields.PickledObjectField(editable=False)),
                ('columns_type_mapping', picklefield.fields.PickledObjectField(editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('encoder_file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='live_scorecards.Encoder')),
                ('raw_feature_transformer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='live_scorecards.LiveDataTransformer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LiveDeploymentPipelineGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pipeline_name', models.CharField(max_length=255)),
                ('common_transformer', models.BooleanField()),
                ('json_type_dict', picklefield.fields.PickledObjectField(editable=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ScorePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_data', models.BinaryField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LiveShapImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_5_features', picklefield.fields.PickledObjectField(editable=False)),
                ('top_5_features_name', picklefield.fields.PickledObjectField(editable=False)),
                ('bottom_5_features', picklefield.fields.PickledObjectField(editable=False)),
                ('bottom_5_features_name', picklefield.fields.PickledObjectField(editable=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LiveScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(max_length=255)),
                ('request_data', picklefield.fields.PickledObjectField(editable=False)),
                ('prediction', models.DecimalField(decimal_places=8, max_digits=15)),
                ('percentile', models.DecimalField(decimal_places=8, max_digits=15)),
                ('monsoon_score', models.DecimalField(decimal_places=8, max_digits=15)),
                ('approved_flag', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='live_scorecards.LiveDeploymentPipelineGroup')),
                ('shap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='live_scorecards.LiveShapImage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LiveDeploymentModelPipeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_first', models.BooleanField()),
                ('pipeline_name', models.CharField(max_length=255)),
                ('common_transformer', models.BooleanField()),
                ('json_type_dict', picklefield.fields.PickledObjectField(editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('live_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='live_scorecards.LiveDeploymentModel')),
                ('model_if_greater_prob', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='if_greater_than_threshold', to='live_scorecards.LiveDeploymentModelPipeline')),
                ('model_if_lower_prob', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='if_lower_than_threshold', to='live_scorecards.LiveDeploymentModelPipeline')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
