# Generated by Django 2.2.3 on 2020-02-25 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('live_scorecards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livedatatransformer',
            name='binary_transformer',
        ),
        migrations.RemoveField(
            model_name='livedeploymentmodelpipeline',
            name='common_transformer',
        ),
        migrations.RemoveField(
            model_name='livedeploymentmodelpipeline',
            name='pipeline_name',
        ),
    ]
