# Generated by Django 2.2.3 on 2020-02-26 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('live_scorecards', '0002_auto_20200225_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livedeploymentmodel',
            name='hard_class_prob_greater',
        ),
        migrations.RemoveField(
            model_name='livedeploymentmodel',
            name='hard_class_prob_lower',
        ),
        migrations.RemoveField(
            model_name='livedeploymentmodelpipeline',
            name='json_type_dict',
        ),
        migrations.AddField(
            model_name='livedeploymentmodelpipeline',
            name='action_if_greater_prob',
            field=models.CharField(
                choices=[
                    ('pred',
                     'Model'),
                    ('true',
                     True),
                    ('false',
                     False),
                    ('exit',
                     None)],
                default='break',
                max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livedeploymentmodelpipeline',
            name='action_if_lower_prob',
            field=models.CharField(
                choices=[
                    ('pred',
                     'Model'),
                    ('true',
                     True),
                    ('false',
                     False),
                    ('exit',
                     None)],
                default='break',
                max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livedeploymentmodelpipeline',
            name='pipeline_group',
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to='live_scorecards.LiveDeploymentPipelineGroup'),
            preserve_default=False,
        ),
    ]
