# Generated by Django 2.2.3 on 2020-02-26 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_scorecards', '0003_auto_20200226_1159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livedeploymentpipelinegroup',
            old_name='pipeline_name',
            new_name='pipeline_group_name',
        ),
        migrations.AlterField(
            model_name='livedeploymentmodelpipeline',
            name='action_if_greater_prob',
            field=models.CharField(
                choices=[
                    ('pred',
                     'Model'),
                    ('true',
                     True),
                    ('false',
                     False),
                    ('break',
                     None)],
                max_length=5),
        ),
        migrations.AlterField(
            model_name='livedeploymentmodelpipeline',
            name='action_if_lower_prob',
            field=models.CharField(
                choices=[
                    ('pred',
                     'Model'),
                    ('true',
                     True),
                    ('false',
                     False),
                    ('break',
                     None)],
                max_length=5),
        ),
    ]
