# Generated by Django 2.2.3 on 2020-02-26 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('live_scorecards', '0004_auto_20200226_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livedeploymentmodel',
            name='encoder_file',
        ),
        migrations.AddField(
            model_name='encoder',
            name='associated_model',
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to='live_scorecards.LiveDeploymentModel'),
            preserve_default=False,
        ),
    ]
