# Generated by Django 2.2.3 on 2020-02-27 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_scorecards', '0005_auto_20200226_1500'),
    ]

    operations = [
        migrations.RenameField(
            model_name='encoder',
            old_name='encoder_pickle',
            new_name='encoder_dict',
        ),
        migrations.AddField(
            model_name='encoder',
            name='encoder_class_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
