# Generated by Django 2.2.3 on 2020-06-04 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('live_scorecards', '0006_auto_20200227_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livescore',
            name='monsoon_score',
            field=models.DecimalField(
                decimal_places=8,
                max_digits=15,
                null=True),
        ),
        migrations.AlterField(
            model_name='livescore',
            name='percentile',
            field=models.DecimalField(
                decimal_places=8,
                max_digits=15,
                null=True),
        ),
        migrations.AlterField(
            model_name='livescore',
            name='shap',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='live_scorecards.LiveShapImage'),
        ),
    ]
