# Generated by Django 2.2.3 on 2020-06-04 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_scorecards', '0007_auto_20200604_0841'),
    ]

    operations = [
        migrations.AddField(
            model_name='livedeploymentmodel',
            name='monsoon_score_max',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='livedeploymentmodel',
            name='monsoon_score_min',
            field=models.IntegerField(null=True),
        ),
    ]
