# Generated by Django 2.2.3 on 2020-06-08 13:26

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('live_scorecards', '0008_auto_20200604_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livedeploymentpipelinegroup',
            name='json_type_dict',
            field=picklefield.fields.PickledObjectField(
                editable=False,
                null=True),
        ),
    ]
