# Generated by Django 2.2.3 on 2020-06-09 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_scorecards', '0009_auto_20200608_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livescore',
            name='approved_flag',
            field=models.BooleanField(null=True),
        ),
    ]
