# Generated by Django 2.2.3 on 2020-06-28 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_scorecards', '0010_auto_20200609_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='livedeploymentmodel',
            name='explainability_option',
            field=models.CharField(
                choices=[
                    ('shap',
                     'shap'),
                    ('surrogate_model',
                     'surrogate_model')],
                max_length=55,
                null=True),
        ),
    ]
