# Generated by Django 2.2.3 on 2020-09-17 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('live_scorecards', '0011_livedeploymentmodel_explainability_option'),
    ]

    operations = [
        migrations.CreateModel(
            name='Threshold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold_name', models.CharField(max_length=255)),
                ('action_if_greater_prob', models.CharField(choices=[('pred', 'Model'), ('true', True), ('false', False), ('threshold', 'threshold'), ('string', 'string'), ('break', None)], max_length=255)),
                ('action_if_lower_prob', models.CharField(choices=[('pred', 'Model'), ('true', True), ('false', False), ('threshold', 'threshold'), ('string', 'string'), ('break', None)], max_length=255)),
                ('object_reference_if_greater', models.CharField(max_length=255)),
                ('object_reference_if_lower', models.CharField(max_length=255)),
                ('is_first', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ml_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='live_scorecards.LiveDeploymentModel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='livedeploymentmodelpipeline',
            name='action_if_greater_prob',
        ),
        migrations.RemoveField(
            model_name='livedeploymentmodelpipeline',
            name='action_if_lower_prob',
        ),
        migrations.RemoveField(
            model_name='livedeploymentmodelpipeline',
            name='model_if_greater_prob',
        ),
        migrations.RemoveField(
            model_name='livedeploymentmodelpipeline',
            name='model_if_lower_prob',
        ),
        migrations.DeleteModel(
            name='ScorePage',
        ),
    ]
